### ISSUE TITLE
Any plans for 2016 ?

### ISSUE THREAD

**Issue by sam2x** [maritz/nohm#103]
Hi @maritz 

Just an "issue" to know if you have any plans about nohm for this years ? i guess you have a lot of works, but could you please keep us informed about this project ? i'm using it with some homemade features, but it would be great to see more activity (from everyone) on this project. I'm sure there still are potentials to unleash from it.

Something to watch closely : 
10-11 May Redis Conf(http://redisconference.com/)

Regards,

**Comment by maritz** [comment]
I have no specific plans at all.

There are many things one could do. Some of the open issues and pull requests need to be resolved and a 1.0.0 release would be cool. A few of the functions are in dire need to be rewritten and the admin panel I've been working on has been going nowhere.

We'll see, I guess.

**Comment by sam2x** [comment]
Hey, thanks for your switf answer.

Yeah i may push some PR. I need to get familiar with travis tests to submit decent PR.
Woah nice for the admin panel, are you using https://github.com/marmelab/ng-admin ?

**Comment by sam2x** [comment]
I have made two feature on my side : 

- zlink/zunlink (link/unlink object in zset datatype, allow me to store a score with it, which define the state of my relation(state may be a timestamp or others integer informations).

- regexp capability in find feature, for string properties who are unique/indexed. (i can give more info about the logic)

Let me know if you're interested about a PR

**Comment by maritz** [comment]
Sure :+1:

**Comment by maritz** [comment]
I created #106 to have a more definitive and general discussion about this.
