### ISSUE TITLE
defaultValue function is invoked when finding an existing object

### ISSUE THREAD

**Issue by dorongutman** [maritz/nohm#107]
I have a model.
After a few instances of that model were saved, I added another property to that model - `createdAt`, and configured it with a defaultValue function that uses `new Date()` so it'll represent the date of the creation of that model.

Now, when I get all the instances from the DB, the `createdAt` property in the instances that were saved before that property existed is always the date when I ran the find command.

**Comment by maritz** [comment]
Yes, when no value is found, the defaultValue function is called to create it. If you don't then save that value, it'll still be empty on the next find.

When creating new defaultValues I recommend making a small script that goes through all instances[1] and simply loads & saves them.

[1] if you have extremely large datasets it might not be viable to go through all instances with one find call, but that should be an edge case.

**Comment by sam2x** [comment]
Normal behaviour. Closing this, please reopen if you have any issue with a code sample.
