### ISSUE TITLE
Global Unique property for all properties.

### ISSUE THREAD

**Issue by ibudisteanu** [maritz/nohm#112]
I am using NOHM, which is great, but I am stumbling with one great problem that I can not solve it elegantly.  All my models (topic, forum, user, etc..) have a **Common and Unique property** namely URL slug, and I want the property URL to be global unique and not locally to one model as unique validator does.

This is what the final urls slugs will look like: skyhub.me/URL-slug1 => will get me a Forum from the DB while skyhub.me/URL-slug2 => will get me a Topic from DB.  I want all my URL-slugs to don't have a prefix.

I wrote my own validation `validateUniqueURL` (that uses a separate Redis hash table), but everytime when I save/update/delete, I have to update the Hash table manually with its corresponding function.

Is there any global-unique validator already in the NOHM or any way to do it fast and elegantly?

**Comment by maritz** [comment]
There is not.

I'd recommend using something like a uuid or shortid for your slugs. That should make the hash table way pretty usable, right?!

What are the problems you are facing with your implementation? And what would the advantages be to have this in nohm itself?

**Comment by ibudisteanu** [comment]
Hi maritz, it is an interesting idea, but at the moment I am not very sure about the ways to implement it.

This is how I did so far (but it is not ideally because it requires a lot of code).

Before, I create (saving) the model for the first time, I generate a unique slug (in case their is one already, I add a sufix extending the slug). I've built a Hash Class extended from Redis client that verify the existence in a separate hash list for my slug. 

I built a unique-slug-validation function which validates me for not creating a duplicate URL slug.

After, I create the model successfully, I store the slug be to used in Hash List and its' value is the ID of the model.

This is the solution:

```
        forum.p(
            {
                title: sTitle,
                URL: await(URLHashHelper.getFinalNewURL(sTitle,null)), //Getting a NEW URL
```
```
            forum.save(function (err) {
                if (err) {
                    console.log("==> Error Saving Forum");
                    resolve({result:"false", errors: forum.errors });
                } else {
                    forum.keepURLSlug(); 
```

Extending the Forum Model with this function:
```
    methods: {
        keepURLSlug : function (sOldURL,  bDelete){

            var URLHashHelper = require ('../../../common/URLs/helpers/URLHash.helper.ts');
            return URLHashHelper.replaceOldURL(sOldURL, this.p('URL'), this.id, bDelete);
        }
    }
```

The problem is that, every time I do an update/create/delete for the model, I need to call the function keepURLSlug()

**Comment by maritz** [comment]
Sorry, I'm assuming this is too old to be useful. If there are any open questions, I'll try my best to help, however I'd need more information on what the problem is.
