### ISSUE TITLE
Support for ioredis(redis-client lib)

### ISSUE THREAD

**Issue by admirkadriu** [maritz/nohm#120]
Does nohm support ioredis?

**Comment by maritz** [comment]
I haven't tested it myself. From a quick glance at the README of ioredis, it looks compatible.

If you want, you could clone the repo, change the tests to use ioredis instead of node_redis and then run the tests. That should give you a good idea, on whether it works or not.

**Comment by admirkadriu** [comment]
Hi @maritz, thank you for the response. 

I tested with ioredis. It works in a way, meaning that the keys are set in db, but there are some errors e.g. it considers that the client is not connected because different APIs for connection status checking.

**Comment by sam2x** [comment]
It may be great if we can in proper way figureout the list of incompatible/missing API of ioredis. 1 year ago I made it  somehow works for some tests. Afaik it was missing some specific API that I was used (stream). I didnt continue with it...

**Comment by maritz** [comment]
A compatibility layer could be implemented, to abstract away the differences.

Is there any specific reason you'd prefer nohm using ioredis? 
You can still use ioredis for every other part of your app and just include node-redis for the nohm initialization.

**Comment by sam2x** [comment]
They claim to be performance-focused and full-featured. I would be interested to see benchmark of thunk-redis vs node_redis vs ioredis : 

This benchmark is interesting but a bit old (not using last version of these 3 projects)  : https://github.com/thunks/thunk-redis/issues/12

**Comment by maritz** [comment]
Certainly worth investigating.

I'd also really be interested if anyone has any real-world metrics of a case where nohm was slowing down an application. I haven't gotten to that scale with any of my personal projects yet, so I don't have any clue how important performance improvements could be.

**Comment by maritz** [comment]
Alright, cluster/sentinel support is a pretty big reason to make nohm ioredis compatible.

**Comment by maritz** [comment]
Published in v2.2.0.

Cluster/Sentinel has not been tested yet, so if anyone wants to test it and runs into problems, please create another issue.

Also note that performance appears to be worse with ioredis.
