### ISSUE TITLE
unlinkAll doesn't work in case of the key including hyphen character

### ISSUE THREAD

**Issue by nfyfamr** [maritz/nohm#125]
Hi.
I'v got trouble with using nohm v0.9.8
I've create a model that generate its id as uuid/v4.
When I call remove method on instance of that model, an error occurred: 
    Uncaught TypeError: Cannot read property '1' of null
        at node_modules/nohm/lib/relations.js:233:29

After some reading the code, I found the reason why it make error.
Because that cannot recognize hyphen character.
So I'm suggesting search pattern of line num 233 be changed from  
`'/:([\w]*):([\w]*):[\w]+$/i'` 
to  
`'/:([^\ :]*):([^\ :]*):[^\ :]+$/i'`

This searches all character sequence excluding whitespace and delimiter colon.
I hope as soon as possible this issue to be solved.

**Comment by maritz** [comment]
Already fixed in v2. (although only for the id part, because v2 ids are uuid by default - docs definitely need to make it more clear that model and relation names must be [\w]+).

PR with tests for v1 are welcome.

**Comment by nfyfamr** [comment]
Ok thanks I'll make it after

**Comment by maritz** [comment]
Fixed in v1.0.0 and docs are changed to mention modelName and relation name constraints.

**Comment by nfyfamr** [comment]
Thanks martiz, you made my works more easier by this.
