### ISSUE TITLE
does relationship supports cascade deleting?

### ISSUE THREAD

**Issue by fatfatson** [maritz/nohm#136]
it seems the foreign objects and their relation keys are left after the primary object has deleted,
is this the right result now?

**Comment by maritz** [comment]
When you remove() on an instance, all its relations should also be removed. However the foreign objects remain, yes.

If you can provide some more information about which cases leave relation keys intact, that would be great. There are some tests for it, but possibly not enough.

**Comment by maritz** [comment]
@fatfatson I'm assuming the problem is resolved.

If not, please re-open the issue. :-)
