### ISSUE TITLE
WARNING: setClient() received a redis client that is not connected yet

### ISSUE THREAD

**Issue by octopusOnJellyfish** [maritz/nohm#184]
Hi, i am having this error showing up after updating node-redis to V4.

{
  message: 'WARNING: setClient() received a redis client that is not connected yet.\n' +
    'Consider waiting for an established connection before setting it. Status (if ioredis): undefined\n' +
    ', connected (if node_redis): undefined',
  name: 'Nohm Error'
}

**Comment by maritz** [comment]
Duplicate of #66
