### ISSUE TITLE
notEmpty validation fails for integer fields with 0 value

### ISSUE THREAD

**Issue by exortech** [maritz/nohm#85]
The implementation of the notEmpty check validates that the value is not falsy. That is different than checking if the value is empty. It fails for various cases like 0 values and other falsy values.

**Comment by maritz** [comment]
> even still, null or undefined would never get resolved to zero.

Actually yes, that is exactly what happens during type casting:

```javascript
case 'integer':
case 'int':
  return isNaN(parseInt(newValue, 10)) ? 0 : parseInt(newValue, 10);
case 'float':
case 'number':
  return isNaN(parseFloat(newValue)) ? 0 : parseFloat(newValue);
```

I've also updated the notEmpty validator documentation to indicate that it is not suitable for number types.
