### ISSUE TITLE
Is nohm support concurrence  and connection pool share only one model define?

### ISSUE THREAD

**Issue by jackiesun8** [maritz/nohm#86]
concurrence is say multi machine connect to a redis(or a redis cluster).
connection pool is say a machine that have a redis pool connected to redis(or a redis cluster).
Thanks to answer.

**Comment by sam2x** [comment]
Just to add a note about clustering support. Actually, Nohm rely on [node-redis lib](https://github.com/NodeRedis/node_redis), however there is [no clustering feature](https://github.com/NodeRedis/node_redis/issues/574) in it. 

Apparently there are two main solutions to this: 

1. migrate to the new [iosredis](https://github.com/luin/ioredis), which offers a [full-featured redis client](https://github.com/luin/ioredis#features). Plus, it's actively maintened; 
2. Use [clustr](https://github.com/gosquared/redis-clustr), a wrapper to node_redis lib, which describe itself as "It tries to be as unobtrusive as possible - mimicing the behaviour of the node_redis client."
