### ISSUE TITLE
hash password

### ISSUE THREAD

**Issue by ralph-rush** [maritz/nohm#88]
i have user `model` with property `password`
i want to hash password only once of course
but when i use script from example
```javascript
password:{
    type:function(value){
        return hash(value);
    }
}
```
the password is hashed when writing and when reading
i cannot compare value with hashed value because i am using bcrypt and random salt generation
how to verify in property function what we are doing in specified time (creating?, updating?, reading?)
is there a way?

**Comment by maritz** [comment]
Use the load_pure property to make sure type casting is not used when reading. [More info](http://maritz.github.io/nohm/#properties)

There is an [example here](https://github.com/maritz/nohm/blob/master/examples/rest-user-server/UserModel.js) that kinda works. I has however not been updated in a while, so be careful.

**Comment by ralph-rush** [comment]
aha! thanks
