### ISSUE TITLE
load model with id

### ISSUE THREAD

**Issue by camel-chased** [maritz/nohm#90]
when i use load method i get only params that i have created but there is no id
i know that to load model i must have id :) but sometimes it is easier to have id already in loaded data 
when i have a lot of "rows" i must create a loop to insert id to each row and always remember to store id before exporting it somewhere else

**Comment by ralph-rush** [comment]
https://github.com/ralph-rush/nohm/commit/f06ddbc5fc352ad5b2285449283a5382a617ca6e

**Comment by maritz** [comment]
When you load a model you get back the instance of the model in `this`. There you can also read the id.
