### ISSUE TITLE
Find and load all

### ISSUE THREAD

**Issue by johngeorgewright** [maritz/nohm#96]
At the moment `findAndLoad()` works differently if you don't specify search criteria:

``` js
MyModel.findAndLoad({key: 'value'}, function (err, models) {
  console.log(models); // [{id: 'id1}, {id: 'id2'}]
});

MyModel.findAndLoad(function (err, models) {
  console.log(models); // ['id1', 'id2']
});
```

I'm guessing this is a bug.

**Comment by maritz** [comment]
Yes, most definitely. Sorry for the long wait.

You wouldnt happen to have a PR for this? Otherwise it'll take me a couple of days at least. :/

**Comment by sam2x** [comment]
solved, waiting merge for PR  #111

**Comment by fatfatson** [comment]
the usage of `findAndLoad` in example is not working now,
if no condition given, it will throw a `not found` exception,
but I'd like to get all the instances.

**Comment by maritz** [comment]
Fixed in v2 by default, merged the test sam2x supplied.
