### ISSUE TITLE
setExtraValidations paths relative to nohm.js module

### ISSUE THREAD

**Issue by mlaco** [maritz/nohm#98]
Please forgive my ignorance if I'm missing something simple. I am new to Node.js.

I wanted to use an external file for validations of my Nohm model, so I tried:

`nohm.setExtraValidations('sightValidations.js');`

with the relevant file in the appropriate location; this resulted in errors like:

```
< module.js:340
<     throw err;
<
<        ^
< Error: Cannot find module 'customValidation'
<     at Function.Module._resolveFilename (module.js:338:15)
<     at Function.Module._load (module.js:280:25)
<     at Module.require (module.js:364:17)
<     at require (module.js:380:17)
<     at Nohm.setExtraValidations (/Users/morgan/Dev/pineapple/node_modules/nohm/lib/nohm.js:196:24)
<     at Array.forEach (native)
<     at Function.Nohm.setExtraValidations (/Users/morgan/Dev/pineapple/node_modules/nohm/lib/nohm.js:192:9)
<     at Object.<anonymous> (/Users/morgan/Dev/pineapple/app/models/sight.js:5:6)
<     at Module._compile (module.js:456:26)
<     at Object.Module._extensions..js (module.js:474:10)
```

After debugging, I realized that module.js was looking for the file relative to nohm.js, rather than relative to `/app/models/sight.js`. I confirmed this by replacing the previous line with

`nohm.setExtraValidations('../../../app/validations/sightValidations.js');`

which gave me access to the custom validations.

**Comment by maritz** [comment]
Yes, that is pretty normal. Nohm has no idea where your files live.  
The propery way to handle paths relative to your project depends on where in your project you are and what kind of philosophies you follow.

The following examples assume execution in models/sight.js and this file structure:

```
app
├──node_modules
│      └──nohm/...
├──nohm_validators
│      └──sightValidations.js
└──models
        └──sight.js
```

One way is to use `__dirname` which is always relative to your current file:

```javascript
nohm.setExtraValidations(__dirname+'/../validations/sightValidations.js');
```

Others advocate the usage of either a GLOBAL or an environment variable:

```javascript
nohm.setExtraValidations(process.env.APP_ROOT+'/validations/sightValidations.js');
```

Some people just keep a custom package in their node_modules that they can require to handle relative files:

```javascript
var app_root = require('my_app_root'); // this just exports a string that points to the app_root
nohm.setExtraValidations(app_root+'/validations/sightValidations.js');
```

Or use a dedicated npm package that does it for you like app-root-path.
See http://stackoverflow.com/questions/10265798/determine-project-root-from-a-running-node-js-application and http://allanhortle.com/2015/02/04/store-your-client-code-in-node_modules.html for some more information and options.

Reopen if you have any further issues. :)

**Comment by mlaco** [comment]
Thank you very much for your assistance, @maritz ; that helps me out!
